# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "en1: Wi-Fi (Airport)"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
        vb.gui = false
        vb.memory = "1024"
      end

      node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    end
  end

end
