# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #manager
  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.box = "bento/ubuntu-16.04"
    manager.vm.network "private_network", ip: "192.168.33.10"

    # Opsional. Edit sesuai dengan nama network adapter di komputer
    # node.vm.network "public_network", bridge: "en1: Wi-Fi (Airport)"

    manager.vm.provider "virtualbox" do |vb|
      vb.name = "manager"
      vb.gui = false
      vb.memory = "512"
    end

    manager.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
  end

  #data node
  (1..2).each do |i|
    config.vm.define "data#{i}" do |node|
      node.vm.hostname = "data#{i}"
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      # node.vm.network "public_network", bridge: "en1: Wi-Fi (Airport)"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "data#{i}"
        vb.gui = false
        vb.memory = "512"
      end

      node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    end
  end

  #proxy
  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "proxy"
    proxy.vm.box = "bento/ubuntu-16.04"
    proxy.vm.network "private_network", ip: "192.168.33.13"

    # Opsional. Edit sesuai dengan nama network adapter di komputer
    # node.vm.network "public_network", bridge: "en1: Wi-Fi (Airport)"

    proxy.vm.provider "virtualbox" do |vb|
      vb.name = "proxy"
      vb.gui = false
      vb.memory = "512"
    end

    proxy.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
  end
end
